import 'express-async-errors'; // Must be first import
import express from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import { config } from './config.js';
import { IntegrationService } from './integrationService.js';
import { Models } from './models.js';
import { requestLogger } from './logger.js';
import rateLimit from 'express-rate-limit';
import { MetricsService } from './metrics.js';
import { cacheMiddleware, cacheUtils } from './cache.js';
import { validate, validateQuery, schemas } from './validation.js';
import { healthCheckMiddleware } from './shutdown.js';
import apiRoutes from './routes/api.js';
import v2Routes from './routes/v2.js';
import authRoutes from './routes/auth.js';
import paymentRoutes from './routes/payments.js';
import connectRoutes from './routes/connect.js';
import connectWebhooks from './routes/connectWebhooks.js';
import { AuthService } from './services/authService.js';

const app = express();

// Security middleware
app.use(helmet());

// Compression middleware (before other middleware)
app.use(compression({
  filter: (req, res) => {
    if (req.headers['x-no-compression']) {
      return false;
    }
    return compression.filter(req, res);
  },
  level: 6, // Compression level (0-9)
  threshold: 1024, // Only compress responses > 1KB
}));

// CORS configuration
app.use(cors({
  origin: config.corsOrigin || '*',
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'x-paypal-signature', 'x-paypal-transmission-time', 'x-plaid-signature', 'x-plaid-timestamp'],
}));

const publicLimiter = rateLimit({
  windowMs: config.rateLimiting.windowMs,
  max: config.rateLimiting.max,
  standardHeaders: true,
  legacyHeaders: false,
});

const webhookLimiterConfig = {
  windowMs: config.rateLimiting.windowMs,
  max: config.rateLimiting.webhookMax,
  standardHeaders: true,
  legacyHeaders: false,
};
const paypalWebhookLimiter = rateLimit(webhookLimiterConfig);
const plaidWebhookLimiter = rateLimit(webhookLimiterConfig);

app.use(bodyParser.json({ verify: rawBodySaver }));
app.use(requestLogger);
app.use(['/webhooks', '/integrations/plaid'], publicLimiter);

async function requireUser(req, res, next) {
  const user = await authenticate(req);
  if (!user) {
    req.log.warn('auth_missing_or_invalid');
    return res.status(401).json({ error: 'unauthorized' });
  }
  req.user = user;
  next();
}

async function requireAdmin(req, res, next) {
  const user = await authenticate(req);
  if (!user || user.role !== 'admin') {
    req.log.warn('admin_required');
    return res.status(403).json({ error: 'forbidden' });
  }
  req.user = user;
  next();
}

async function authenticate(req) {
  const authHeader = req.headers.authorization || '';
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;
  if (!token) return null;
  
  // Support legacy static tokens for backward compatibility
  if (token === config.auth.adminToken) return { id: 'admin', role: 'admin' };
  if (token === config.auth.userToken) return { id: 'user', role: 'user' };
  
  // JWT authentication
  const user = await AuthService.verifyAndGetUser(token);
  if (user) {
    return { id: user.id, role: user.role, email: user.email };
  }
  
  return null;
}

app.get('/health', healthCheckMiddleware, (req, res) => {
  req.log.info('health_check');
  const metrics = IntegrationService.getMetrics();
  const cacheStats = cacheUtils.getStats();
  res.json({ 
    status: 'ok', 
    metrics,
    cache: {
      keys: cacheStats.keys,
      hits: cacheStats.hits,
      misses: cacheStats.misses,
      ksize: cacheStats.ksize,
      vsize: cacheStats.vsize,
    },
    uptime: process.uptime(),
    memory: process.memoryUsage(),
  });
});

app.post('/integrations/subscribe', validate(schemas.createSubscription), (req, res) => {
  const { userId = 'demo-user', planId = 'pro' } = req.body || {};
  const subscription = IntegrationService.createSubscription({
    userId,
    planId,
    correlationId: req.correlationId,
    source: 'subscription_api',
  });
  req.log.info('subscription_created', { userId, planId });
  MetricsService.emitEvent({
    eventType: 'subscription.requested',
    userId,
    correlationId: req.correlationId,
    source: 'subscription_api',
    properties: { planId },
  });
  
  // Invalidate entitlements cache for this user
  cacheUtils.invalidatePattern(`/entitlements?userId=${userId}`);
  
  res.json(subscription);
});

app.post('/integrations/plaid/link-token', validate(schemas.plaidLinkToken), (req, res) => {
  // Token generated by backend; client never sees secrets.
  const token = `plaid-sandbox-${Date.now()}`;
  req.log.info('plaid_link_token_issued', { userId: req.body?.userId });
  MetricsService.emitEvent({
    eventType: 'plaid.link_token_issued',
    userId: req.body?.userId || 'demo-user',
    correlationId: req.correlationId,
    source: 'plaid',
  });
  res.json({ link_token: token });
});

app.post('/integrations/plaid/exchange', validate(schemas.plaidExchange), (req, res) => {
  const { publicToken, userId = 'demo-user' } = req.body || {};
  const itemId = `item-${Date.now()}`;
  Models.plaidItems.set(itemId, { id: itemId, userId, publicToken, accessToken: 'server-only' });
  req.log.info('plaid_public_token_exchanged', { userId, itemId });
  MetricsService.emitEvent({
    eventType: 'plaid.connected',
    userId,
    correlationId: req.correlationId,
    source: 'plaid',
    properties: { itemId },
  });
  res.json({ item_id: itemId });
});

app.post('/webhooks/paypal', paypalWebhookLimiter, (req, res) => {
  try {
    const signature = req.header('x-paypal-signature') || '';
    const timestamp = req.header('x-paypal-transmission-time') || req.requestTimestamp;
    const rawBody = req.rawBody || JSON.stringify(req.body || {});
    const result = IntegrationService.verifyAndProcessPayPalWebhook(
      rawBody,
      signature,
      timestamp,
      req.log,
      req.correlationId,
    );
    res.status(200).json({ status: result.status });
  } catch (err) {
    req.log.error('paypal_webhook_error', { error: err.message });
    res.status(400).json({ error: 'invalid_signature' });
  }
});

app.post('/webhooks/plaid', plaidWebhookLimiter, (req, res) => {
  try {
    const signature = req.header('x-plaid-signature') || '';
    const timestamp = req.header('x-plaid-timestamp') || req.requestTimestamp;
    const rawBody = req.rawBody || JSON.stringify(req.body || {});
    const result = IntegrationService.verifyAndProcessPlaidWebhook(
      rawBody,
      signature,
      timestamp,
      req.log,
      req.correlationId,
    );
    res.status(200).json({ status: result.status });
  } catch (err) {
    req.log.error('plaid_webhook_error', { error: err.message });
    res.status(400).json({ error: 'invalid_signature' });
  }
});

// PayPal billing endpoints (simulated)
app.post('/billing/paypal/subscription/create', requireUser, validate(schemas.paypalSubscriptionCreate), (req, res) => {
  const { userId = 'demo-user', planId = 'plan_pro' } = req.body || {};
  const result = IntegrationService.createPayPalSubscription({
    userId,
    planId,
    correlationId: req.correlationId,
    log: req.log,
    source: 'paypal_api',
  });
  req.log.info('paypal_subscription_created', { userId, planId });
  res.json(result);
});

app.post('/billing/paypal/subscription/confirm', requireUser, validate(schemas.paypalSubscriptionConfirm), (req, res) => {
  const { providerSubscriptionId, userId = req.user?.id || 'demo-user' } = req.body || {};
  try {
    const sub = IntegrationService.confirmPayPalSubscription({
      providerSubscriptionId,
      userId,
      correlationId: req.correlationId,
      log: req.log,
    });
    const entitlement = IntegrationService.createEntitlement({
      userId: req.user?.id || userId,
      productId: sub.planId,
      kind: 'plan',
      durationDays: 30,
    });
    
    // Invalidate entitlements cache
    cacheUtils.invalidatePattern(`/entitlements?userId=${userId}`);
    
    res.json({ subscription: sub, entitlement });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.post('/billing/paypal/subscription/cancel', requireUser, validate(schemas.paypalSubscriptionCancel), (req, res) => {
  const { providerSubscriptionId } = req.body || {};
  try {
    const sub = IntegrationService.cancelPayPalSubscription({
      providerSubscriptionId,
      correlationId: req.correlationId,
      log: req.log,
      source: 'paypal_api',
    });
    
    // Invalidate relevant caches
    cacheUtils.invalidatePattern('/entitlements');
    
    res.json({ subscription: sub });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.post('/outbound/dispatch', requireAdmin, async (req, res) => {
  await IntegrationService.dispatchOutboundWebhooks(req.log);
  res.json({ status: 'ok', queueLength: Models.outboundWebhookQueue.length });
});

function rawBodySaver(req, res, buf) {
  req.rawBody = buf.toString();
}


// Catalog and entitlement helpers
const catalog = [
  {
    id: 'plan_pro',
    type: 'plan',
    name: 'Pro Plan',
    price: '$14.99/mo',
    description: 'Advanced analytics, instant payouts, and automation.',
  },
  {
    id: 'addon_shift_insights',
    type: 'addon',
    name: 'Shift Insights',
    price: '$4.99/mo',
    description: 'Per-shift profitability and mileage rollups.',
  },
  {
    id: 'onetime_boost',
    type: 'one_time',
    name: 'Boost Pack',
    price: '$19.99',
    description: 'Priority placement for 14 days.',
  },
];

app.get('/catalog', cacheMiddleware(600), (req, res) => {
  MetricsService.emitEvent({
    eventType: 'shop.viewed',
    userId: 'demo-user',
    correlationId: req.correlationId,
    source: 'shop',
    properties: { surface: 'catalog' },
  });
  res.json({ products: catalog });
});

app.get('/entitlements', cacheMiddleware(60, (req) => `/entitlements?userId=${req.query.userId || 'demo-user'}`), (req, res) => {
  const userId = req.query.userId || 'demo-user';
  const entitlements = Array.from(Models.entitlements.values()).filter(
    e => e.userId === userId,
  );
  res.json({ entitlements });
});

app.post('/purchase', validate(schemas.purchase), (req, res) => {
  const { productId, userId = 'demo-user' } = req.body || {};
  const product = catalog.find(p => p.id === productId);
  if (!product) {
    return res.status(400).json({ error: 'unknown_product' });
  }
  const entitlement = IntegrationService.createEntitlement({
    userId,
    productId,
    kind: product.type,
    durationDays: product.type === 'one_time' ? 0 : 30,
  });
  req.log.info('purchase_completed', { userId, productId });
  MetricsService.emitEvent({
    eventType: 'checkout.completed',
    userId,
    correlationId: req.correlationId,
    source: 'shop',
    properties: { productId, productType: product.type },
  });
  
  // Invalidate entitlements cache
  cacheUtils.invalidatePattern(`/entitlements?userId=${userId}`);
  
  res.json({ entitlement });
});

app.post('/metrics/events', validate(schemas.metricsEvent), (req, res) => {
  try {
    const { eventType, userId = 'demo-user', ts, properties = {}, correlationId, source } =
      req.body || {};
    const result = MetricsService.emitEvent({
      eventType,
      userId,
      ts,
      properties,
      source: source || 'app',
      correlationId: correlationId || req.correlationId,
    });
    res.json(result);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

app.post('/metrics/rollup/daily', (req, res) => {
  const { asOf } = req.body || {};
  const result = MetricsService.generateDailyRollups(asOf ? new Date(asOf) : new Date());
  res.json(result);
});

app.get('/metrics/rollup/daily', validateQuery(schemas.dailyRollup), cacheMiddleware(300, (req) => {
  const userId = req.query.userId || 'demo-user';
  const date = req.query.date || new Date().toISOString().split('T')[0];
  return `/metrics/rollup/daily?userId=${userId}&date=${date}`;
}), (req, res) => {
  const userId = req.query.userId || 'demo-user';
  const date = req.query.date;
  const rollup = MetricsService.getDailyRollup({ userId, date });
  if (!rollup) {
    MetricsService.generateDailyRollups(date ? new Date(date) : new Date());
  }
  const refreshed = MetricsService.getDailyRollup({ userId, date });
  res.json({ rollup: refreshed });
});

// Auth routes (with stricter rate limiting)
const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 20, // 20 requests per window
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many authentication attempts, please try again later' },
});
app.use('/auth', authLimiter, authRoutes);

// Mount new API routes for gig platforms, advances, benefits, expenses, notifications, and profiles
app.use('/api/v1', apiRoutes);

// Mount V2 feature routes
app.use('/api/v2', v2Routes);

// Payment routes (Stripe)
app.use('/api/payments', paymentRoutes);

// Stripe Connect routes
// These handle connected account creation, onboarding, products, and checkout
app.use('/api/connect', connectRoutes);

// Stripe Connect webhooks
// IMPORTANT: These use raw body for signature verification
// Mount before JSON parsing middleware wouldn't work, but we use rawBodySaver
app.use('/api/connect/webhooks', connectWebhooks);

// Global error handler (must be last)
app.use((err, req, res, next) => {
  req.log?.error('unhandled_error', { 
    error: err.message, 
    stack: err.stack,
    path: req.path,
  });
  
  res.status(err.status || 500).json({
    error: config.env === 'production' ? 'internal_error' : err.message,
    ...(config.env !== 'production' && { stack: err.stack }),
  });
});

export default app;
